config/routes.rb
Rails.application.routes.draw do
  namespace :backend do
    root 'home#index'
    get 'sign' => 'sessions#sign'
    post 'signing' => 'sessions#signing'
    delete 'sign_out' => 'sessions#sign_out'
    resources :admins
  end

  namespace :site, path: '' do
  end

  root 'site/home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  include AuthConcern
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/auth_concern.rb
module AuthConcern
  extend ActiveSupport::Concern

  included do
    has_secure_password

    VAILDATE_MOBILE_FORMAT = /\A?(13[0-9]|15[0-9]|17[0-9]|18[0-9]|14[0-9])[0-9]{8}\z/

    validates :mobile, presence: true, uniqueness: true, length: { is: 11 }, format: { with: VAILDATE_MOBILE_FORMAT }
    validates :nick_name, presence: true, uniqueness: true, length: { maximum: 10, minimum: 3 }
    validates :real_name, presence: true

    before_create { generate_token(:auth_token) }
  end

  # 在每次生成admin或者user时添加auth_token
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while self.class.exists?(column => self[column])
  end
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    layout 'admin'
    protect_from_forgery with: :exception
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/backend/admins_controller.rb
module Backend
  class AdminsController < Backend::ApplicationController
    def index
      @admins = Admin.all.page(params[:page]).per(10)
    end
  end
end

app/controllers/backend/application_controller.rb
module Backend
  class ApplicationController < ActionController::Base
    layout 'backend'
    protect_from_forgery with: :exception

    before_action :current_admin?

    private

      def current_admin?
        redirect_to backend_sign_path if current_admin.blank?
      end

      def current_admin
        @current_admin ||= session[:admin_auth_token] && Admin.find_by(auth_token: session[:admin_auth_token])
      end

      helper_method :current_admin
  end
end

app/controllers/backend/home_controller.rb
module Backend
  class HomeController < Backend::ApplicationController
  end
end

app/controllers/backend/sessions_controller.rb
module Backend
  class SessionsController < Backend::ApplicationController
    layout 'backend_auth'
    skip_before_action :current_admin?, only: [:sign, :signing]

    def signing
      _admin = Admin.find_by(mobile: params[:mobile])
      if _admin && _admin.authenticate(params[:password])
        session[:admin_auth_token] = _admin.auth_token
        redirect_to backend_root_path
      else
        redirect_back(fallback_location: root_path)
      end
    end

    def sign_out
      session[:admin_auth_token] = nil
      reset_session
      redirect_to backend_sign_path
    end
  end
end

app/controllers/site/application_controller.rb
module Site
  class ApplicationController < ActionController::Base
    layout 'site'
    protect_from_forgery with: :exception
  end
end

app/controllers/site/home_controller.rb
module Site
  class HomeController < Site::ApplicationController
    def index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backend/admins_helper.rb
module Backend::AdminsHelper
end

app/helpers/backend/application_helper.rb
module Backend::ApplicationHelper
end

app/helpers/backend/home_helper.rb
module Backend::HomeHelper
end

app/helpers/backend/sessions_helper.rb
module Backend::SessionsHelper
end

app/helpers/backend_helper.rb
module BackendHelper

  def li_names(name)
    case name
    when 'home'
      %w( home )
    when 'customers'
      %w( users heros )
    when 'orders'
      %w( orders )
    when 'admins'
      %w( admins )
    end
  end

  def backend_li_active(li_names, li_name)
    li_names.include?(li_name) ? 'active' : ''
  end
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/backend/admins/_admin.html.slim
- @admins.each do |admin|
  tr
    td = admin.id
    td = admin.mobile
    td = admin.nick_name
    td = admin.real_name
    td
      = link_to t('backend.table.action.show'), '', class: 'btn btn-info btn-split'
      = link_to t('backend.table.action.edit'), '', class: 'btn btn-warning btn-split'
      = link_to t('backend.table.action.destroy'), '', class: 'btn btn-danger btn-split'

app/views/backend/admins/_function_panel.html.slim
section#backend-admins-function-panel
  form.form-inline role="form"
    .form-group
      label.sr-only for="search" = t('backend.search_form.input')
      input#search.form-control placeholder="#{t('backend.search_form.input')}" type="text" /
    button.btn.btn-default type="submit" = t('backend.search_form.btn')

app/views/backend/admins/index.html.slim
section#backend-admins-index
  = render partial: 'page_header'
  = render partial: 'function_panel'

  table.table.table-bordered.table-hover.table-condensed
    thead
      th.col-sm-2 = Admin.human_attribute_name :id
      th.col-sm-3 = Admin.human_attribute_name :mobile
      th.col-sm-2 = Admin.human_attribute_name :nick_name
      th.col-sm-2 = Admin.human_attribute_name :real_name
      th.col-sm-3 = t('backend.table.actions')
    tbody
      = render @admins
      = paginate @admins

app/views/backend/application/_navbar.html.slim
section.admin-application-navbar
  nav.navbar.navbar-default.navbar-fixed-top role="navigation"
    .container
      .navbar-header
        button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href== backend_root_path  = t('backend.application.navbar.hero_coming')
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          li class== backend_li_active(li_names('home'), controller_name)
            a href== backend_root_path  = t('backend.application.navbar.home')
          li.dropdown class== backend_li_active(li_names('customers'), controller_name)
            a.dropdown-toggle data-toggle="dropdown" href="#"
              = t('backend.application.navbar.customers')
              span.caret
            ul.dropdown-menu role="menu"
              li
                a href="#"  = t('backend.application.navbar.users')
              li.divider
              li
                a href="#"  = t('backend.application.navbar.heros')
          li class== backend_li_active(li_names('orders'), controller_name)
            a href="#"  = t('backend.application.navbar.orders')
          li class== backend_li_active(li_names('admins'), controller_name)
            a href== backend_admins_path  = t('backend.application.navbar.admins')

        ul.nav.navbar-nav.navbar-right
          li
            a href="#"
              i.fa.fa-envelope-o
              = t('backend.application.navbar.messages')
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#"
              small
                = t('backend.application.navbar.admin')
                | ：
                = @current_admin.nick_name
              span.caret
            ul.dropdown-menu role="menu"
              li
                a href="#"  = t('backend.application.navbar.add_admin')
              li.divider
              li
                = link_to backend_sign_out_path, method: :delete, data: { confirm: t('backend.application.navbar.confirm_sign_out') } do
                  i.fa.fa-sign-out
                  = t('backend.application.navbar.sign_out')

app/views/backend/application/_page_header.html.slim
section.backend-application-page-header
  .page-header
    h1
      = t('backend.' + controller_name + '.' + action_name )

app/views/backend/home/index.html.slim
section#backend-home-index
  = render partial: 'page_header'

app/views/layouts/admin.html.slim
doctype html
html lang="zh-CN"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="renderer" content="webkit"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title HeroComing
    = csrf_meta_tags
    = stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload'

  body
    = render partial: 'navbar'
    = yield

app/views/layouts/admin_auth.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="renderer" content="webkit"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title HeroComing
    = csrf_meta_tags
    = stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload'

  body
    = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeroComing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/backend.html.slim
doctype html
html lang="zh-CN"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="renderer" content="webkit"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title = t('backend.' + controller_name + '.' + action_name )

    = csrf_meta_tags
    = stylesheet_link_tag    'backend/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'backend/application', 'data-turbolinks-track': 'reload'

  body
    = render partial: 'navbar'
    .container
      = yield

app/views/layouts/backend_auth.html.slim
doctype html
html lang="zh-CN"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="renderer" content="webkit"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title = t('backend.auth.title')

    = csrf_meta_tags
    = stylesheet_link_tag    'backend/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'backend/application', 'data-turbolinks-track': 'reload'

  body
    = yield

app/views/layouts/site.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="renderer" content="webkit"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title HeroComing
    = csrf_meta_tags
    = stylesheet_link_tag    'site/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'site/application', 'data-turbolinks-track': 'reload'

  body
    = yield

app/views/layouts/site_auth.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="renderer" content="webkit"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title HeroComing
    = csrf_meta_tags
    = stylesheet_link_tag    'site/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'site/application', 'data-turbolinks-track': 'reload'

  body
    = yield